name: Export Issue
on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Export Issues
        uses: niteoweb/export-issues-action@v2
        with:
          repo: ${{github.repository}}
          org:  ${{github.repository.owner}}

      - name: production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: issues
          path: "issues/*.md"
