# Action to backup issues using gh2md, contributed by
# https://github.com/0ut0fcontrol.
# See https://github.com/mattduck/gh2md/issues/11.
name: Convert Issue to Markdown
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    
    - name: Backup github issues to a markdown file.
      run: |
        pip3 install --user --upgrade setuptools
        pip3 install --user gh2md
        mkdir myissues
        $HOME/.local/bin/gh2md $GITHUB_REPOSITORY ./myissues/test-issues.md --no-closed-issues
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: GitHub Commit & Push
      uses: actions-js/push@v1.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        author_email: "action@github.com"
        author_name: "GitHub Action"
        message: "Backup all issues into issues.md"
