# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Offline Issues

on: workflow_dispatch

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
    
    - name: Install Offline issues Dependency
      run: npm install -g offline-issues
      
      
    
