# Action to backup issues using gh2md, contributed by
# https://github.com/0ut0fcontrol.
# See https://github.com/mattduck/gh2md/issues/11.
name: Convert Issue to Markdown
on: 
  workflow_dispatch:
    inputs:
      folder-name:
        description: 'name of the folder for markdown file'
        required: False
        default: 'offline-issues'
      file-name:
        description: 'name of markdown file'
        required: False
        default: 'issues'
      commit-message:
        description: 'name of commit'
        required: True
        default: 'Backup all issues into issues.md'
      condition-one:
        description: 'argument condition one'
        required: False
      condition-Two:
        description: 'argument condition Two'
        required: False


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: github issues to a markdown file.
      run: |
        pip3 install --user --upgrade setuptools
        pip3 install --user gh2md
        mkdir ${{ github.event.inputs.folder-name }}
        $HOME/.local/bin/gh2md $GITHUB_REPOSITORY ./${{ github.event.inputs.folder-name }}/${{ github.event.inputs.file-name }}.md `
        --${{ github.event.inputs.condition-one }} 
        -- ${{ github.event.inputs.conditions-two }} `
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: GitHub Commit & Push
      uses: actions-js/push@v1.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        author_email: "38515818+PardusEidolon@users.noreply.github.com"
        author_name: "PardusEidolon"
        message: ${{ github.event.inputs.commit-message }}
