name: Issue Report

on: 
  workflow_dispatch:
    inputs:
      title:
        required: true
        description: 'please give the issue a title'
        default: 'default issue title'

jobs:
  Create-Issue:
    runs-on: ubuntu-latest
    steps:
       - name: checkout repo
         uses: actions/checkout@v2

       - name: Issue Genesis
         uses: actions/github-script@v5
         with:
          script: |
              github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: ${{github.event.inputs.title}},
              body: 'I am a god'
              });
